In [4]:
import numpy as np

# Step 2: Create a 1D array
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array (Fixed missing assignment operator)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Placeholder arrays (Fixed missing assignment operator)
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Add 2 more sample data points
years_exp = np.append(years_exp, [12, 15])
salaries = np.append(salaries, [[110, 120, 130], [140, 150, 160]], axis=0)

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# Subtraction and Division
exp_minus_1 = years_exp - 1
salary_div_10 = salaries / 10

# Apply np.exp() and np.log()
exp_val = np.exp(years_exp)
log_val = np.log(years_exp)

# Fixed indexing to show first two elements of the first row
print("First two salaries:", salaries[0, 0:2])

# Reverse arrays using slicing
reversed_years = years_exp[::-1]

# Slice 2D arrays for subgroups
sub_salaries = salaries[:2, :2] # Top-left 2x2 section
# Reshape into 3x4 if data permits (requires 12 elements)

# Example using arange
new_shape = np.arange(12).reshape(3, 4)

# Multiply salaries by a scaling factor (e.g., 1.10 for 10% raise)
scaled_salaries = salaries * 1.10

# Compute median and 75th percentile
median_exp = np.median(years_exp)
percentile_75 = np.percentile(years_exp, 75)
# Use sqrt and custom function
sqrt_salaries = np.sqrt(salaries)

def custom_bonus(x):
    return x + (x * 0.05)

bonus_applied = np.apply_along_axis(custom_bonus, 0, salaries)

First two salaries: [50 60]


In [21]:
import pandas as pd
data = np.random.randint(1, 50, size=(5, 3))
# Fixed syntax error in DataFrame creation
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

In [22]:
# Add new calculated column
df_data['Sum_XY'] = df_data['X'] + df_data['Y']
df_data.to_csv('modified_data.csv', index=False)

In [23]:
import numpy as np

STUDENT_NAME = "Andrei"
STUDENT_ID = 251298

# Item 1
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
print("Mean:", np.mean(data), "Std Dev:", np.std(data))

# Item 2
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
print("Row sums:", np.sum(matrix, axis=1))
print("Column sums:", np.sum(matrix, axis=0))

Andrei's Array: [105  20 101  23 109 146 119   4  17  32]
Mean: 67.6 Std Dev: 50.14419208642213
Andrei's Matrix:
 [[20 59 23 18]
 [ 4 17 50 32]
 [34 44 44 25]]
Row sums: [120 103 147]
Column sums: [ 58 120 117  75]


In [24]:
# Item 5: Matrix Multiplication and Determinant
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
product = A @ B
det_A = np.linalg.det(A)
print("Matrix A @ B:\n", product)
print("Determinant of A:", det_A)

# Item 7: Stepped Slicing
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0 # Sets specific grid patterns to 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Matrix A @ B:
 [[3030 2228]
 [ 992  967]]
Determinant of A: -996.9999999999999
Andrei's Modified 4x4 Array:
 [[ 0 59  0 18]
 [ 4 17 50 32]
 [ 0 44  0 25]
 [ 9 19 19 28]]


In [25]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = (arr % 2 == 0)
arr[mask] = -1
print("Array with even numbers replaced by -1:\n", arr)

Array with even numbers replaced by -1:
 [[-1 59 23]
 [-1 -1 17]
 [-1 -1 -1]]


In [26]:
import pandas as pd

# Item 11: DataFrame Creation
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
print(df)

# Item 12: Grouping (Fixed Column Name spacing)
avg_salary = df.groupby('Name')['Score'].mean() # Using Score as proxy for example
print(avg_salary)

     Name  Score  YearsCodePro
0  Andrei    133            22
1  Andrei     67             3
2  Andrei    106            16
3  Andrei     70            16
4  Andrei     65            17
Name
Andrei    88.2
Name: Score, dtype: float64
