In [1]:
import numpy as np

# Step 2: Create a 1D array
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array (Fixed missing assignment operator)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Placeholder arrays (Fixed missing assignment operator)
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

ModuleNotFoundError: No module named 'numpy'

In [88]:
# Add 2 more sample data points
years_exp = np.append(years_exp, [12, 15])
salaries = np.append(salaries, [[110, 120, 130], [140, 150, 160]], axis=0)

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [89]:
# Subtraction and Division
exp_minus_1 = years_exp - 1
salary_div_10 = salaries / 10

# Apply np.exp() and np.log()
exp_val = np.exp(years_exp)
log_val = np.log(years_exp)

# Fixed indexing to show first two elements of the first row
print("First two salaries:", salaries[0, 0:2])

# Reverse arrays using slicing
reversed_years = years_exp[::-1]

# Slice 2D arrays for subgroups
sub_salaries = salaries[:2, :2] # Top-left 2x2 section
# Reshape into 3x4 if data permits (requires 12 elements)

# Example using arange
new_shape = np.arange(12).reshape(3, 4)

# Multiply salaries by a scaling factor (e.g., 1.10 for 10% raise)
scaled_salaries = salaries * 1.10

# Compute median and 75th percentile
median_exp = np.median(years_exp)
percentile_75 = np.percentile(years_exp, 75)
# Use sqrt and custom function
sqrt_salaries = np.sqrt(salaries)

def custom_bonus(x):
    return x + (x * 0.05)

bonus_applied = np.apply_along_axis(custom_bonus, 0, salaries)

First two salaries: [50 60]


In [90]:
import pandas as pd
data = np.random.randint(1, 50, size=(5, 3))
# Fixed syntax error in DataFrame creation
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

In [91]:
# Add new calculated column
df_data['Sum_XY'] = df_data['X'] + df_data['Y']
df_data.to_csv('modified_data.csv', index=False)

In [92]:
import numpy as np

STUDENT_NAME = "Andrei"
STUDENT_ID = 251298

# Item 1
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
print("Mean:", np.mean(data), "Std Dev:", np.std(data))

# Item 2
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
print("Row sums:", np.sum(matrix, axis=1))
print("Column sums:", np.sum(matrix, axis=0))

Andrei's Array: [105  20 101  23 109 146 119   4  17  32]
Mean: 67.6 Std Dev: 50.14419208642213
Andrei's Matrix:
 [[20 59 23 18]
 [ 4 17 50 32]
 [34 44 44 25]]
Row sums: [120 103 147]
Column sums: [ 58 120 117  75]


In [93]:
# Item 5: Matrix Multiplication and Determinant
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
product = A @ B
det_A = np.linalg.det(A)
print("Matrix A @ B:\n", product)
print("Determinant of A:", det_A)

# Item 7: Stepped Slicing
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0 # Sets specific grid patterns to 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Matrix A @ B:
 [[3030 2228]
 [ 992  967]]
Determinant of A: -996.9999999999999
Andrei's Modified 4x4 Array:
 [[ 0 59  0 18]
 [ 4 17 50 32]
 [ 0 44  0 25]
 [ 9 19 19 28]]


In [94]:
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = (arr % 2 == 0)
arr[mask] = -1
print("Array with even numbers replaced by -1:\n", arr)

Array with even numbers replaced by -1:
 [[-1 59 23]
 [-1 -1 17]
 [-1 -1 -1]]


In [95]:
import pandas as pd

# Item 11: DataFrame Creation
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
print(df)

# Item 12: Grouping (Fixed Column Name spacing)
avg_salary = df.groupby('Name')['Score'].mean() # Using Score as proxy for example
print(avg_salary)

     Name  Score  YearsCodePro
0  Andrei    133            22
1  Andrei     67             3
2  Andrei    106            16
3  Andrei     70            16
4  Andrei     65            17
Name
Andrei    88.2
Name: Score, dtype: float64


In [96]:
import numpy as np

STUDENT_NAME = "Andrei"
STUDENT_ID = 251298

# Item 1
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
print("Mean:", np.mean(data), "Std Dev:", np.std(data))

Andrei's Array: [105  20 101  23 109 146 119   4  17  32]
Mean: 67.6 Std Dev: 50.14419208642213


In [97]:
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
print("Row sums:", np.sum(matrix, axis=1))
print("Column sums:", np.sum(matrix, axis=0))

Andrei's Matrix:
 [[20 59 23 18]
 [ 4 17 50 32]
 [34 44 44 25]]
Row sums: [120 103 147]
Column sums: [ 58 120 117  75]


In [98]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3)) 
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d) 
 
slice_mid = arr3d[:,1,:] 
print("Slice[:,1,:]:\n", slice_mid) 


Andrei's 3D Array:
 [[[21  8 19]
  [26  4 22]
  [12 17 22]]

 [[ 3 16 16]
  [17  1 12]
  [ 8 11 11]]

 [[24 13 12]
  [ 8 22 18]
  [ 0 18 23]]]
Slice[:,1,:]:
 [[26  4 22]
 [17  1 12]
 [ 8 22 18]]


In [99]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)] 
print(f"{STUDENT_NAME}'s Original:", x) 
print("Filtered subset:", filtered) 


Andrei's Original: [105  20 101  23 109 146 119   4  17  32]
Filtered subset: []


In [100]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
print("Matrix A:\n", A) 
print("Matrix B:\n", B) 
 
product = A @ B 
det_A = np.linalg.det(A) 
print("A @ B:\n", product) 
print("Determinant of A:", det_A) 


Matrix A:
 [[20 59]
 [23 18]]
Matrix B:
 [[ 4 17]
 [50 32]]
A @ B:
 [[3030 2228]
 [ 992  967]]
Determinant of A: -996.9999999999999


In [101]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
angles = np.linspace(0, 2*np.pi, 8) 
sine_vals = np.sin(angles) 
cos_vals = np.cos(angles) 
print(f"{STUDENT_NAME}'s Angles:", angles) 
print("Sine:", sine_vals) 
print("Cosine:", cos_vals) 


Andrei's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [102]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, 
                        size=(4,4))
arr[::2, ::2] = 0 
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr) 


Andrei's Modified 4x4 Array:
 [[ 0 59  0 18]
 [ 4 17 50 32]
 [ 0 44  0 25]
 [ 9 19 19 28]]


In [103]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10) 
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail') 
print(f"{STUDENT_NAME}'s Scores:", scores) 
print("Grades:", grades) 


Andrei's Scores: [104  19 100  22 108 145 118   3  16  31]
Grades: ['Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Fail']


In [104]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, 
                        size=(3,4)) 
flat_arr = arr.flatten() 
transposed_arr = arr.T 
print("Original array:\n", arr) 
print("Flattened:", flat_arr) 
print("Transposed:\n", transposed_arr) 


Original array:
 [[20 59 23 18]
 [ 4 17 50 32]
 [34 44 44 25]]
Flattened: [20 59 23 18  4 17 50 32 34 44 44 25]
Transposed:
 [[20  4 34]
 [59 17 44]
 [23 50 44]
 [18 32 25]]


In [105]:
import numpy as np 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3)) 
mask = arr % 2 == 0 
arr[mask] = -1 
print("Array with conditional replacements:\n", arr) 


Array with conditional replacements:
 [[-1 59 23]
 [-1 -1 17]
 [-1 -1 -1]]


In [106]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name': [STUDENT_NAME]*5, 
    'Score': np.random.randint(STUDENT_ID%50, 
                               STUDENT_ID%100+50,5), 
                               'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
                               }) 
print(df) 


     Name  Score  YearsCodePro
0  Andrei    133            22
1  Andrei     67             3
2  Andrei    106            16
3  Andrei     70            16
4  Andrei     65            17


In [107]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'], 
    # Corrected to use a functional salary range, e.g., 40000 to 150000 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
    }) 
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean() 
print(avg_salary) 


EdLevel
Bachelor    132743.5
Master       82726.0
PhD          91475.0
Name: ConvertedComp, dtype: float64


In [108]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
top5 = df.sort_values(by='ConvertedComp', ascending=False) 
print(top5) 


       Country  ConvertedComp
0  Philippines         148501
3       Canada         116986
2           UK          91475
1          USA          86952
4      Germany          78500


In [109]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name':[STUDENT_NAME]*5, 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
high_exp = df[df['YearsCodePro']>STUDENT_ID%10] 
print(high_exp) 


     Name  YearsCodePro
0  Andrei            21
2  Andrei            19
3  Andrei            26


In [110]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)}) 
 
bins = [0, 50000, 100000, 150000, 200000] 
labels = ['0-50k', '50-100k', '100-150k', '>150k'] 
 
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels) 
print(df) 


   ConvertedComp   Bracket
0         148501  100-150k
1          86952   50-100k
2          91475   50-100k
3         116986  100-150k
4          78500   50-100k


In [111]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
 
# Original Code Issue:  
np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)  
 
# Corrected Code: Using a functional salary range (40000 to 150000) 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)}) 
 
df['LogComp'] = np.log(df['ConvertedComp']) 
print(df) 


   ConvertedComp    LogComp
0         136118  11.821277
1          95555  11.467457
2          99376  11.506666
3          70129  11.158092
4          95327  11.465068


In [112]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5), 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
corr_matrix = df.corr() 
print(corr_matrix) 


               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.501993
ConvertedComp      0.501993       1.000000


In [113]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
# Calculate mean, median, and standard deviation for each 'EdLevel' 
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std'])
summary = summary.reset_index()
print(summary) 


    EdLevel      mean    median           std
0  Bachelor  132743.5  132743.5  22284.470209
1    Master   82726.0   82726.0   5976.466515
2       PhD   91475.0   91475.0           NaN


In [114]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
 
# Generate salaries: [100727, 136195, 130612, 100727, 95233] 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)}) 
 
threshold = 110000 
 
# Create the 'HighPay' column using np.where() 
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No') 
 
print(df) 


   ConvertedComp HighPay
0         148501     Yes
1          86952      No
2          91475      No
3         116986     Yes
4          78500      No


In [115]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Andrei" 
STUDENT_ID = 251298 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5) 
}) 
 
# Group by 'Country' and calculate the mean and max 'ConvertedComp' 
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max']) 
print(top_countries) 


                 mean     max
Country                      
Canada       116986.0  116986
Germany       78500.0   78500
Philippines  148501.0  148501
UK            91475.0   91475
USA           86952.0   86952
